// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saawdvkyhrnpkyekvzhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYXdkdmt5aHJucGt5ZWt2emh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzM1MTcsImV4cCI6MjA2MTUwOTUxN30.aF4EE35sxFj_ZB8w1mlGoEh-LDnz_7h2Jv7krg49aIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);